---
- name: ServiceNow Incident Remediation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    sn_instance: "https://dev341769.service-now.com"
    # These custom mappings will be different for certain versions of ServiceNow.  Look at your ServiceNow instance for these Choice lists
    custom_incident_state_mapping:
      # ServiceNow table: sys_choice.  Query for the incident state choices: element=state^name=incident
      # URL example: https://<Your_instance>.service-now.com/sys_choice_list.do?sysparm_query=element%3Dstate%5Ename%3Dincident&sysparm_view=
      state:
        1: new
        2: in_progress
        3: on_hold
        6: resolved
        7: closed
        8: cancelled
        new: new
        in_progress: in_progress
        on_hold: on_hold
        resolved: resolved
        closed: closed
        cancelled: cancelled
      # ServiceNow table: sys_choice.  Query for the incident close_code choices: element=close_code^name=incident
      # URL example: https://<Your_instance>.service-now.com/sys_choice_list.do?sysparm_query=element%3Dclose_code%5Ename%3Dincident&sysparm_view=
      close_code:
        "Workaround provided": "Workaround provided"
        "Duplicate": "Duplicate"
        "Resolved by change": "Resolved by change"
        "User error": "User error"
        "Known error": "Known error"
        "Resolved by problem": "Resolved by problem"
        "No resolution provided": "No resolution provided"
        "Resolved by request": "Resolved by request"
        "Resolved by caller": "Resolved by caller"
        "Solution provided": "Solution provided"
        "Solution Provided": "Solution Provided" # handle case variance
        # Add empty string mapping for initial state
        "":""

  tasks:
    - name: Display incident information
      ansible.builtin.debug:
        msg:
          - "========================================"
          - "ServiceNow Incident Automation Triggered"
          - "========================================"
          - "Incident Number: {{ incident_number }}"
          - "Description: {{ short_description }}"
          - "Priority: {{ priority }}"
          - "CI: {{ cmdb_ci }}"
          - "State: {{ state }}"
          - "Assigned To: {{ assigned_to }}"
          - "Category: {{ category }}"
          - "sys_id: {{ sys_id }}"
          - "========================================"
    
    - name: Determine remediation action based on incident
      ansible.builtin.set_fact:
        remediation_type: "{{ 'disk_cleanup' if 'disk' in short_description|lower else 'generic' }}"
    
    - name: Execute disk cleanup remediation
      ansible.builtin.debug:
        msg: "Running disk cleanup on {{ cmdb_ci }}"
      when: remediation_type == 'disk_cleanup'
      # Add actual remediation tasks here
    
    - name: Execute generic remediation
      ansible.builtin.debug:
        msg: "Running generic diagnostics on {{ cmdb_ci }}"
      when: remediation_type == 'generic'
      # Add actual remediation tasks here
    
    - name: Update ServiceNow incident with results
      ansible.builtin.uri:
        url: "{{ sn_instance }}/api/now/table/incident/{{ sys_id }}"
        method: PATCH
        headers:
          Content-Type: "application/json"
        user: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        force_basic_auth: true
        body_format: json
        body:
          work_notes: "Ansible automation completed at {{ now(utc=true).isoformat() }}"
        validate_certs: false
        status_code: 200
      when: sys_id is defined
      register: servicenow_update

    - name: Log ServiceNow update result
      ansible.builtin.debug:
        msg: "ServiceNow incident {{ incident_number }} updated successfully"
      when: servicenow_update is succeeded

    - name: Close Complete the incident
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        sys_id: "{{ sys_id }}"
        incident_mapping: "{{ custom_incident_state_mapping }}"
        state: closed
        close_code: "Solution provided" # Use EXACT string from ServiceNow choices
        close_notes: "Closed"
      register: incident_closure

    - name: Print Incident closure info
      ansible.builtin.debug:
        msg: 
          - "======== Incident Closure Information ==========="
          - "Incident Number: {{ incident_closure.record.number }}"
          - "Incident State: {{ incident_closure.record.state }}"
          - "Incident Close Code: {{ incident_closure.record.close_code }}"
          - "Incident URL: {{ sn_instance }}/incident.do?sys_id={{ incident_closure.record.sys_id }}"
