---
- name: ServiceNow Incident Automation - Simple Test
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        
  rules:
    - name: Log All Incoming Incidents
      condition: event.payload.event_type == "incident_created"
      action:
        debug:
          msg: |
            New Incident from ServiceNow:
            Number: {{ event.payload.incident_number }}
            Description: {{ event.payload.short_description }}
            Priority: {{ event.payload.priority }}
            CI: {{ event.payload.cmdb_ci }}
            Sys ID: {{ event.payload.sys_id }}

# ---
# - name: ServiceNow Event Processing
#   hosts: all
#   sources:
#     - ansible.eda.range:
#         # This is a simple built-in event source for demonstration purposes
#         limit: 5
        
#   rules:
#     - name: Say Hello on event 1
#       # The condition checks on event payload. The 'range' source sends events with an 'i' key
#       condition: event.i == 1
#       # The action to run when the condition is true
#       action:
#         debug:
#           msg: "Hello! Event {{ event.i }} received"
